enableImmutableInstalls: false

enableTelemetry: false

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmmirror.com"

npmScopes:
  vanilla-extract:
    npmRegistryServer: "https://registry.yarnpkg.com"
