#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Load NVM and Node.js
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# lint js/ts files
echo 🧿 Running file linter...
npx lint-staged

# format svg
echo 🧿 Running svg formatter...
for file in `git diff --diff-filter=ACMRT --cached --name-only | grep ".svg\$"`
    do 
        echo "Formatting $file" 
        ./node_modules/.bin/svgo -q $file 
        git add $file
    done

echo ✅ All pre-commit jobs are done
